name:                helf
version:             0.2.0.0
github:              "https://github.com/TobiasPleyer/HElf.git"
license:             BSD3
author:              "Tobias Pleyer"
maintainer:          "example@example.com"
copyright:           "2018 Tobias Pleyer"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/TobiasPleyer/HElf.git#README.md>

dependencies:
- base >= 4.7 && < 5
- mmap
- array

library:
  source-dirs: src
  include-dirs: include
  other-extensions:
  - CPP
  - ForeignFunctionInterface
  - OverloadedStrings
  - RecordWildCards

executables:
  helf:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - helf

tests:
  helf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - helf
